packages:
  - apps/*

injectWorkspacePackages: true

onlyBuiltDependencies:
  - '@firebase/util'
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - core-js-pure
  - esbuild
  - prisma
  - protobufjs
  - sharp
  - unrs-resolver

syncInjectedDepsAfterScripts:
  - build
