/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * Server API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HealthControllerCheck200ResponseInfoValue } from './HealthControllerCheck200ResponseInfoValue';
import {
    HealthControllerCheck200ResponseInfoValueFromJSON,
    HealthControllerCheck200ResponseInfoValueFromJSONTyped,
    HealthControllerCheck200ResponseInfoValueToJSON,
    HealthControllerCheck200ResponseInfoValueToJSONTyped,
} from './HealthControllerCheck200ResponseInfoValue';

/**
 * 
 * @export
 * @interface HealthControllerCheck200Response
 */
export interface HealthControllerCheck200Response {
    /**
     * 
     * @type {string}
     * @memberof HealthControllerCheck200Response
     */
    status?: string;
    /**
     * 
     * @type {{ [key: string]: HealthControllerCheck200ResponseInfoValue; }}
     * @memberof HealthControllerCheck200Response
     */
    info?: { [key: string]: HealthControllerCheck200ResponseInfoValue; } | null;
    /**
     * 
     * @type {{ [key: string]: HealthControllerCheck200ResponseInfoValue; }}
     * @memberof HealthControllerCheck200Response
     */
    error?: { [key: string]: HealthControllerCheck200ResponseInfoValue; } | null;
    /**
     * 
     * @type {{ [key: string]: HealthControllerCheck200ResponseInfoValue; }}
     * @memberof HealthControllerCheck200Response
     */
    details?: { [key: string]: HealthControllerCheck200ResponseInfoValue; };
}

/**
 * Check if a given object implements the HealthControllerCheck200Response interface.
 */
export function instanceOfHealthControllerCheck200Response(value: object): value is HealthControllerCheck200Response {
    return true;
}

export function HealthControllerCheck200ResponseFromJSON(json: any): HealthControllerCheck200Response {
    return HealthControllerCheck200ResponseFromJSONTyped(json, false);
}

export function HealthControllerCheck200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthControllerCheck200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'info': json['info'] == null ? undefined : (mapValues(json['info'], HealthControllerCheck200ResponseInfoValueFromJSON)),
        'error': json['error'] == null ? undefined : (mapValues(json['error'], HealthControllerCheck200ResponseInfoValueFromJSON)),
        'details': json['details'] == null ? undefined : (mapValues(json['details'], HealthControllerCheck200ResponseInfoValueFromJSON)),
    };
}

export function HealthControllerCheck200ResponseToJSON(json: any): HealthControllerCheck200Response {
    return HealthControllerCheck200ResponseToJSONTyped(json, false);
}

export function HealthControllerCheck200ResponseToJSONTyped(value?: HealthControllerCheck200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'info': value['info'] == null ? undefined : (mapValues(value['info'], HealthControllerCheck200ResponseInfoValueToJSON)),
        'error': value['error'] == null ? undefined : (mapValues(value['error'], HealthControllerCheck200ResponseInfoValueToJSON)),
        'details': value['details'] == null ? undefined : (mapValues(value['details'], HealthControllerCheck200ResponseInfoValueToJSON)),
    };
}

